Mobike/Mobike/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('administracion.urls'))
]

Mobike/administracion/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static



app_name = 'administracion'

urlpatterns = [ 
    path('', views.inicio, name="inicio"),
    path('registro/', views.registro, name="registro"),
    path('sesion/', views.sesion,  name="sesion"),
    path('sesion_usuario/', views.sesion2,  name="sesion2"),
    path('cuenta_admin/', views.cuenta, name="cuenta_admin"),
    path('cuenta_usuario/<str:id_usuario>', views.cuentaUsuario, name="cuenta_usuario"),
    path('cuenta_funcionario/', views.cuenta_funcionario, name="cuenta_funcionario"),
    path('calificacion/<str:id_usuario>', views.calificacion, name="calificacion"),
    path('reportes/', views.reportes, name="reportes"),
    path('miperfil/<str:id_usuario>/', views.Miperfil, name="perfil"),
    path('misdatos/<str:id_usuario>', views.datos, name="datos"),
    path('listar/', views.listar, name="listar"),
    path('editar_usuario/<str:id_usuario>', views.editar, name="editar"),
    path('bloquear_usuario/<str:id_usuario>', views.bloquear, name="bloquear"),
    path('usuario_ya_actualizado/<str:id_usuario>', views.actualizar, name="ya_actualizado"),
    path('usuario_ya_bloqueado/', views.bloquear, name="ya_bloqueado"),
    path('registro/registro_exitoso/', views.registroexitoso, name="ya_registrado"),
    path('yamodificado/', views.datos, name="ya_mod"),
    path('arriendo/<str:id_usuario>', views.arriendo, name="arriendo"),
    path('bici_disponible/<int:id_e>/<str:id_usuario>', views.bicis, name="bicis"),
    path('codigo_verificacion/<str:cod>/<str:id_usuario>', views.codigo, name="ingreso_codigo"),
    path('arriendo_encurso/<str:cod>/<str:id_usuario>', views.encurso, name="encurso"),
    path('arriendo_realizado/<str:id_usuario>', views.arriendo_realizado, name="arriendo_realizado"),
    path('cambio_direccion/<str:id_usuario>', views.direccion, name="direccion"),
    path('cambio_pass/<str:id_usuario>', views.cambiopass, name="cambiopass"),
    path('mistransacciones/<str:id_usuario>', views.mistransacciones, name="mistransacciones"),
    path('mismediopago/<str:id_usuario>', views.mediospago, name="mediospago"),
    path('tarjeta/<str:id_usuario>/<str:id_tarjeta>', views.tarjeta_eliminar, name="tarjeta"),
    path('nuevatarjeta/<str:id_usuario>', views.agregartarjeta, name="agregartarjeta"),
    path('t_eliminada/<str:id_usuario>', views.t_ya_eliminada, name="ya_eliminada"),
    
    
]

Mobike/administracion/models.py
from django.db import models
from datetime import datetime, time
now= time()
Hora = now.hour
minuto = now.minute
segundo = now.second
class Region(models.Model):
    region= models.CharField(max_length=100)
    def __str__(self):
        return self.region

class Ciudad(models.Model):
    ciudad= models.CharField(max_length=100)
    region = models.ForeignKey(Region, on_delete=models.CASCADE)
    def __str__(self):
        return self.ciudad

class Comuna(models.Model):
    comuna = models.CharField(max_length=100)
    ciudad = models.ForeignKey(Ciudad, on_delete=models.CASCADE)

    def __str__(self):
        return self.comuna

class Banco(models.Model):
    nombre_banco = models.CharField(max_length=100)
    def __str__(self):
        return self.nombre_banco


class MedioPago(models.Model):
    tarjeta = models.CharField(max_length=25, primary_key=True)
    codigo_seguridad = models.CharField(max_length=3)
    fecha_vencimiento = models.CharField(max_length=3)
    banco = models.ForeignKey(Banco, on_delete=models.CASCADE)
    

class Usuario(models.Model):
    rut_usuario= models.CharField(max_length=20, primary_key=True)
    nombres= models.CharField(max_length=100)
    apellidos= models.CharField(max_length=100)
    direccion= models.CharField(max_length=100)
    comuna = models.ForeignKey(Comuna, on_delete=models.CASCADE)
    ciudad= models.ForeignKey(Ciudad, on_delete=models.CASCADE)
    region= models.ForeignKey(Region, on_delete=models.CASCADE)
    email= models.EmailField(max_length=254)
    telefono= models.CharField(max_length=100)
    contrass= models.CharField(max_length=20)
    estado = models.CharField(max_length=20)
    calificacion = models.CharField(max_length=200)
    

    def __str__(self):
        return self.nombres

class Administrador(models.Model):
    rut_administrador = models.CharField(max_length=20, primary_key=True)
    nombre_admin = models.CharField(max_length=100)
    usuario_admin = models.CharField(max_length=100)
    contrass= models.CharField(max_length=20)

    def __str__(self):
        return self.nombre_admin

class UsuarioMobike(models.Model):
    usuario = models.CharField(max_length=20)
    tarjetaPago = models.CharField(max_length=25, primary_key=True )

class Estacion(models.Model):
    ubicacion = models.CharField(max_length=20)
    def __str__(self):
        return self.ubicacion

class Funcionario(models.Model):
    rut_funcionario = models.CharField(max_length=20, primary_key=True)
    nombre_funcionario = models.CharField(max_length=100)
    usuario_funcionario = models.CharField(max_length=100)
    contrass = models.CharField(max_length=20)

class Arriendo(models.Model):
    id_arriendo = models.CharField(max_length=200, primary_key=True)
    ubicacion_origen = models.CharField(max_length=200)
    ubicacion_termino = models.CharField(max_length= 200)
    hora_inicio = models.CharField(max_length=30, default=str(Hora)+":"+str(minuto)+":"+str(segundo), editable=False)
    hora_termino = models.CharField(max_length=30, default=str(now.hour + 1)+":"+str(now.minute)+":"+str(now.second), editable=False)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    costo = models.CharField(max_length=30)


class Bicicleta(models.Model):
    numero_bicicleta = models.CharField(max_length=10)
    estado_bicicleta = models.CharField(max_length=10)
    codigo_bicicleta = models.CharField(max_length=10)
    estacion_bicicleta = models.ForeignKey(Estacion, on_delete=models.CASCADE)


class Calificacion(models.Model):
    nombre_calificacion = models.CharField(max_length=50)

Mobike/administracion/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import *
from datetime import datetime, time


def inicio(request):
    return render(request, "administracion/inicio.html")


def registro(request):
    comunas = Comuna.objects.all()
    ciudades = Ciudad.objects.all()
    regiones = Region.objects.all()
    bancos = Banco.objects.all()
    c= request.POST.get('region')
    if request.method == 'GET':
        contexto = {'comunas': comunas, 'ciudades': ciudades, 'regiones': regiones, 'bancos': bancos, 'c': c}
        return render(request, "administracion/registro.html", contexto)

    elif request.method == 'POST':

        medioPago = MedioPago()
        medioPago.tarjeta = request.POST.get('tarjeta_banco')

        Banco_ob = request.POST.get('banco')
        banco_tarjeta = Banco.objects.get(pk = Banco_ob)
        medioPago.banco = banco_tarjeta
        medioPago.codigo_seguridad = request.POST.get('codigo_seguridad')
        medioPago.fecha_vencimiento = request.POST.get('fecha_tarjeta')
        medioPago.save()

        usuariog = Usuario()
        usuariog.rut_usuario = request.POST.get('rut')
        usuariog.nombres = request.POST.get('nombres') 
        usuariog.apellidos = request.POST.get('apellidos')
        usuariog.direccion = request.POST.get('direccion')

        region_us = Region.objects.get( region = request.POST.get('region'))
        usuariog.region = region_us

    
        ciudad_us = Ciudad.objects.get( ciudad = request.POST.get('ciudad'))
        usuariog.ciudad = ciudad_us


        comuna_us = Comuna.objects.get( comuna = request.POST.get('comuna'))
        usuariog.comuna = comuna_us

        usuariog.email = request.POST.get('email')
        usuariog.telefono = request.POST.get('telefono')
        contrauno = request.POST.get('pass')
        usuariog.contrass = contrauno
        usuariog.estado = 'Activo'
        usuariog.calificacion = 'Sin calificación'

        usuariog.save()

        usuarioM = UsuarioMobike()
        usuarioM.usuario = request.POST.get('rut')
        usuarioM.tarjetaPago = request.POST.get('tarjeta_banco')

        usuarioM.save()

        contexto = {'usuario' : usuariog,
            'comunas': comunas,
                        'ciudades': ciudades,
                        'regiones': regiones,
                        'bancos': bancos}
        return render(request, "administracion/registroexitoso.html", contexto)
            
            

        

    return render(request, "administracion/registro.html")

def registroexitoso(request):
    return render(request, 'administracion/registroexitoso.html')

def sesion(request):
    administrador = Administrador.objects.filter(usuario_admin= request.POST.get('user_admin')).exists()
    funcionario = Funcionario.objects.filter(usuario_funcionario= request.POST.get('user_admin')).exists()
    if request.method == 'POST' and administrador == False | funcionario == False:
        mensaje_error = "Credenciales ingresadas no son correctas"
        return render(request, "administracion/sesion.html", {'m': mensaje_error})

    if request.method == 'POST':
            ad = request.POST.get('user_admin')
            ps = request.POST.get('contrasenia_admin')

            if Administrador.objects.filter(usuario_admin= ad).exists() == True:
                admin_user = Administrador.objects.get(usuario_admin= ad)
                a = admin_user.usuario_admin
                c = admin_user.contrass
                n = admin_user.nombre_admin
                contexto = {'nombre_admin': n}
                if ad == a and ps == c:
                    return render(request, "administracion/cuenta_admin.html", contexto)
                else:
                    mensaje_error = "Credenciales ingresadas no son correctas"
                    return render(request, "administracion/sesion.html", {'m': mensaje_error})

            if Funcionario.objects.filter(usuario_funcionario= ad).exists() == True:
                admin_user = Funcionario.objects.get(usuario_funcionario = ad)
                a = admin_user.usuario_funcionario
                c = admin_user.contrass
                n = admin_user.nombre_funcionario
                contexto = {'nombre_admin': n}
                if ad == a and ps == c:
                    return render(request, "administracion/cuenta_func.html", contexto)
                else:
                    mensaje_error = "Credenciales ingresadas no son correctas"
                    return render(request, "administracion/sesion.html", {'m': mensaje_error})

    return render(request, "administracion/sesion.html")


def sesion2(request):
    usuario = Usuario.objects.filter(pk = request.POST.get('user')).exists()
    if request.method == 'POST' and usuario == False:
        mensaje_error = "Credenciales ingresadas no son correctas"
        return render(request, "administracion/sesion2.html", {'m': mensaje_error})     

    if request.method == 'POST':
        us = request.POST.get('user')
        uc = request.POST.get('contrasenia')
        user_registrado = Usuario.objects.get(rut_usuario = us)
        uss = user_registrado.rut_usuario
        ucc = user_registrado.contrass
        unn = user_registrado.nombres
        upp = user_registrado.apellidos
        ues = user_registrado.estado
        comunas = Comuna.objects.all()
        ciudades = Ciudad.objects.all()
        regiones = Region.objects.all()
        bancos = Banco.objects.all()
        comuna_mod = Comuna.objects.get(comuna = user_registrado.comuna)
        ciudad_mod = Ciudad.objects.get(ciudad= user_registrado.ciudad)
        region_mod = Region.objects.get(region= user_registrado.region) 
       

        contexto_usuario = {'ur': user_registrado, 'unn': unn, 'ciudades': ciudades, 'comunas': comunas,
        'regiones': regiones, 'bancos': bancos, 'comunamod': comuna_mod, 'ciudadmod': ciudad_mod, 'regionmod':region_mod}
        if us == uss and uc == ucc and ues == 'Activo':
            return render(request, "administracion/cuenta_usuario.html", contexto_usuario)
        

        else:
            mensaje_error = "Credenciales ingresadas no son correctas"
            return render(request, "administracion/sesion2.html", {'m': mensaje_error})            
    return render(request, "administracion/sesion2.html")
    


def cuenta(request):
    return render(request, 'administracion/cuenta_admin.html')

def cuentaUsuario(request, id_usuario):
    us = Usuario.objects.get(pk = id_usuario)
    return render(request, 'administracion/cuenta_usuario.html', {'ur': us})

def cuenta_funcionario(request):
    return render(request, 'administracion/cuenta_func.html')

def calificacion(request, id_usuario):
    us = Usuario.objects.get(pk = id_usuario)
    calificaciones = Calificacion.objects.all()
    if request.method == 'POST':
        us.calificacion = request.POST.get('calificacion')
        us.save()
        mensaje = "ok"
        return render(request, 'administracion/calificacion.html', {'usuario': us, 'calificaciones': calificaciones, 'mensaje' :mensaje})
        

    return render(request, 'administracion/calificacion.html', {'usuario': us, 'calificaciones': calificaciones})

def reportes(request):
    usuario = Usuario.objects.all()
    arriendos = Arriendo.objects.all()   
    cod_arriendo = ""
    if request.method == 'POST':
        if request.POST.get('buscar_codigo'):
            cod_arriendo = request.POST.get('buscar_codigo')
            arr = arriendos.filter(id_arriendo = cod_arriendo)
            if Arriendo.objects.filter(id_arriendo= cod_arriendo).exists() == True:    
                return render(request, 'administracion/reportes.html', {'todos': arr, 'arriendo': cod_arriendo, 'usuarios':usuario})
            else:
                m= "error"
                return render(request, 'administracion/reportes.html', {'todos': arriendos, 'arriendo': cod_arriendo, 'usuarios':usuario,'m':m})

         
        if request.POST.get('buscar_usuario'):
            cod_arriendo = request.POST.get('buscar_usuario')
            arr = arriendos.filter(usuario= cod_arriendo)
            mensaje = "ok"
            if Arriendo.objects.filter(usuario= cod_arriendo).exists() == True:
                return render(request, 'administracion/reportes.html', {'todos': arr, 'arriendo': cod_arriendo, 'mensaje' :mensaje, 'usuarios':usuario})
            else:
                m= "error"
                return render(request, 'administracion/reportes.html', {'todos': arriendos, 'arriendo': cod_arriendo, 'usuarios':usuario,'m':m})

        if request.POST.get('buscar_ubicacion_inicio'):
            cod_arriendo = request.POST.get('buscar_ubicacion_inicio')
            arr = arriendos.filter(ubicacion_origen= cod_arriendo)
            if Arriendo.objects.filter(ubicacion_origen= cod_arriendo).exists() == True:
                return render(request, 'administracion/reportes.html', {'todos': arr, 'arriendo': cod_arriendo, 'usuarios':usuario})
            else:
                m= "error"
                return render(request, 'administracion/reportes.html', {'todos': arriendos, 'arriendo': cod_arriendo, 'usuarios':usuario,'m':m})


        if request.POST.get(''):
            arriendos = Arriendo.objects.all()
            return render(request, 'administracion/reportes.html', {'todos': arriendos, 'usuarios':usuario})

    return render(request, 'administracion/reportes.html', {'todos':arriendos,'usuarios':usuario})


def Miperfil(request, id_usuario):
    user = Usuario.objects.get(pk = id_usuario)
    return render(request, 'administracion/miperfil.html', {'user': user})



def datos(request, id_usuario):
    comunas = Comuna.objects.all()
    ciudades = Ciudad.objects.all()
    regiones = Region.objects.all()

    usuario_mod = Usuario.objects.get(rut_usuario= id_usuario)
    comuna_mod = Comuna.objects.get(comuna = usuario_mod.comuna)
    ciudad_mod = Ciudad.objects.get(ciudad= usuario_mod.ciudad)

Mobike/administracion/templates/administracion/cuenta_func.html
{% extends "administracion/base.html" %}
{% load static %}
{%block head%}
CUENTA ADMINISTRADOR
{%endblock%}

{% block content%}

<div class="container">
<h1>Bienvenido !</h1>
    <hr>
    <h3>TAREAS</h3>
     <div class="form-row">
        <div class="col">
            <a class="btn btn-primary " name="ir-reportes" href="{% url 'administracion:reportes' %}" role="button">Generar reportes</a>
        </div>
    </div>    
    <hr>


<a id="cerrar" href="{% url 'administracion:inicio' %}"><strong>Cerrar Sesion</strong></a>
</div>

{% endblock %}

Mobike/administracion/templates/administracion/cuenta_usuario.html
{% extends "administracion/base.html" %}
{% load static %}
{%block head%}
CUENTA USUARIO
{%endblock%}

{% block content%}
<section  class= "container">
    <h1>Bienvenido ! </h1>
    <hr>
    <img class="rounded mx-auto d-block" src="{% static 'administracion/img/7.jpg'%}" alt="...">
    <p class="nombre_u">{{ur.nombres}} {{ur.apellidos}}</p>
    <div class="col text-center">
    <a class ="btn btn-warning" href ="{% url 'administracion:perfil' ur.rut_usuario %}">Mi perfil</a>
    </div>
    <br>
    <div class="col text-center">
    <a class ="btn btn-primary" href ="{% url 'administracion:arriendo' ur.rut_usuario %}" name="irarriendo">COMENZAR ARRIENDO</a>
    <a class ="btn btn-primary" href ="{% url 'administracion:mistransacciones' ur.rut_usuario %}" name="mistransacciones">MIS ARRIENDOS</a>
    </div>
    <hr>
    <a  href="{% url 'administracion:inicio'  %}"><strong>Cerrar Sesion</strong></a>
    </section>


{% endblock %}

Mobike/administracion/templates/administracion/ingreso_codigo.html
{% extends "administracion/base.html" %}
{% load static %}
{%block head%}
BICICLETAS
{%endblock%}
{%block script %}
 <script>

            $(function()
            {
                 $("#formulario-codigo").validate(
                     {
                  rules: { 
                          codigo_des: {required : true}
                          },

                  messages : { 
                          codigo_des: {required: "Es necesario ingresar el codigo"}
                            }
                          }
                          );
            })


    

 </script>

{% endblock %}

{% block content%}
<section  class= "container">
    <form  method ="POST" id="formulario-codigo">
        {% csrf_token %}
        <div id="codigov" class="text-center" >
            <h3>INGRESA ESTE CODIGO PARA DESBLOQUEAR TU BICICLETA</h3>
            <br>
            <br>
            <h1 id="codigo_base_desbloqueo"><strong>{{bici.codigo_bicicleta}}</strong></h1>
            <br>
            <br>
            <input type="text" name="codigo_des" id="codigo_des"class="form-control" placeholder="Ingrese su codigo aqui">
            <br>
            <br>

            <button type="submit" id="v_codigo" class="btn btn-warning">Validar Codigo</button>
            <br>
            {% if cod %}
            <a class="btn btn-success mt-5" href="{% url 'administracion:encurso' bici.estacion_bicicleta_id usuario.rut_usuario %}" type="submit" id="comenzarriendo" >COMENZAR ARRIENDO</a>
             {% else %}
            <button class="btn btn-success mt-5" href="{% url 'administracion:encurso' bici.estacion_bicicleta_id usuario.rut_usuario %}" type="button" id="comenzarriendo" disabled>COMENZAR ARRIENDO</button>
             {% endif %}
            

        </div>

            <a href="{% url 'administracion:bicis' bici.estacion_bicicleta_id usuario.rut_usuario %}"><strong id ="volverabicis">Volver</strong></a>

            <br>
            <br>
    </form>
        {% if m %}
          <div class="alert alert-danger" role="alert">
                {{m}}
        </div>
        {% endif %}
</section>



{% endblock %}

Mobike/administracion/templates/administracion/mediospago.html
{% extends "administracion/base.html" %}
{% load static %}
{%block head%}
MEDIOS DE PAGO
{%endblock%}
{%block script %}
 <script>

   

            $(function alertaNoEliminar()
            {
                $("#no_poder_eliminar").on("click", function ()
                {
                    var l = document.getElementById("alerta-no-eliminar");
                    l.innerHTML= `<div class="alert alert-warning" role="alert">
                                   No puedes alterar esta tarjeta, debes tener al menos un medio de pago ingresado
                                   </div>`
                }
                );
            })


 </script>

{% endblock %}

{% block content%}
<section  class= "container col-6" >
<h1>MIS MEDIOS DE PAGO</h1>
<a name="agregarcartarjeta" class="btn btn-primary  mb-5" type="button" href ="{% url 'administracion:agregartarjeta' usuario.rut_usuario %}">Agregar tarjeta</a>
<br>

{% if tarjetas.count > 1 %}
<form class="form-inline my-2 my-lg-0 " method="POST" action="" id="medios-de-pago">
 {% csrf_token %}
 
   
      <input name="buscartarjeta" class="form-control mr-sm-2" type="search" placeholder="Buscar tarjeta" aria-label="Buscar">
      <button name="filtrotarjeta" class="btn btn-outline-primary my-2 my-sm-0 ml-2" type="submit">Buscar</button>
      <button name="refrescartarjeta" class="btn btn-outline-primary my-2 my-sm-0 ml-2" type="submit">REFRESCAR</button>
       {% if m %}  
        <div class="alert alert-warning ml-5" role="alert">
        ¡ No se encontraron registros !
      </div>
        {% endif %}  
<table id ="tabla_tarjeta" class="table table-sm table-bordered mt-5" >
  <thead>
    <tr>
      <th scope="col">Numero Tarjeta</th>
      <th scope="col">Accion</th>

    </tr>
  </thead>
  <tbody>
  {% for t in tarjetas %}
    <tr>
        <th scope="row">{{t.tarjetaPago}}</th>
        <td><a href="{% url 'administracion:tarjeta' usuario.rut_usuario t.tarjetaPago  %}"class ="btn btn-success" type="button" name="tarjeta_eliminar" id="tarjeta_eliminar">Ir a Eliminar</a></td>
        
      </tr>
  {% endfor %}

  </tbody>
</table>
 <a href="{% url 'administracion:cuenta_usuario' usuario.rut_usuario  %}"><strong id ="cancelar">Volver</strong></a>

    </form>

{% else %}

<form class="form-inline my-2 my-lg-0 " method="POST" action="" id="medios-de-pago" readonly>
 {% csrf_token %}
 
   
      <input name="buscartarjeta" class="form-control mr-sm-2" type="search" placeholder="Buscar tarjeta" aria-label="Buscar">
      <button name="filtrotarjeta" class="btn btn-outline-primary my-2 my-sm-0 ml-2" type="submit">Buscar</button>
      <button name="refrescartarjeta" class="btn btn-outline-primary my-2 my-sm-0 ml-2" type="submit">REFRESCAR</button>
     {% if m %}  
        <div class="alert alert-warning ml-5" role="alert">
        ¡ No se encontraron registros !
      </div>
        {% endif %} 

<table id ="tabla_tarjeta" class="table table-sm table-bordered mt-5" >
  <thead>
    <tr>
      <th scope="col">Numero Tarjeta</th>
      <th scope="col">Accion</th>

    </tr>
  </thead>
  <tbody>
  {% for t in tarjetas %}
    <tr>
        <th scope="row">{{t.tarjetaPago}}</th>
        <td><a class ="btn btn-success" type="button" name="no_poder_eliminar" id="no_poder_eliminar">Ir a Eliminar</a></td>
        
      </tr>
  {% endfor %}

  </tbody>
</table>
 <a href="{% url 'administracion:cuenta_usuario' usuario.rut_usuario  %}"><strong id ="cancelar">Volver</strong></a>

    </form>

{% endif %}

<div id="alerta-no-eliminar">
</div>
       
</section>

{% endblock %}

Mobike/administracion/templates/administracion/miperfil.html
{% extends "administracion/base.html" %}
{% load static %}
{%block head%}
CUENTA USUARIO
{%endblock%}

{% block content%}

<section  class= "container">
<div class="row">
    <div class ="col">
        <h1>Mis Datos</h1>
        <h3>CALIFICACION ACTUAL: {{user.calificacion}}</h3>
        <p>Rut: {{user.rut_usuario}}</p>
        <p>Nombres: {{user.nombres}}</p>
        <p>Apellidos: {{user.apellidos}}</p>
        <p>Direccion: {{user.direccion}}</p>
        <p>Email {{user.email}}</p>
        <p>Telefono: {{user.telefono}}</p>
        <p>Comuna: {{user.comuna}}</p>
        <p>Ciudad: {{user.ciudad}}</p>
        <p>Region {{user.region}}</p>
        <a href="{% url 'administracion:cuenta_usuario' user.rut_usuario %}"><strong id ="cancelar">Volver</strong></a>

    </div>
    <div class ="col">
    <a class ="btn btn-warning mt-2" href ="{% url 'administracion:datos' user.rut_usuario %}">Actualizar Datos</a>
    <br>
    <a class ="btn btn-warning mt-2" href ="{% url 'administracion:direccion' user.rut_usuario %}">Actualizar Direccion</a>
    <br>
    <a class ="btn btn-warning mt-2" href ="{% url 'administracion:cambiopass' user.rut_usuario %}">Actualizar Contraseña</a> 
    <br> 
    <a class ="btn btn-warning mt-2" href ="{% url 'administracion:mediospago' user.rut_usuario %}">Mis Medios de Pago</a>  
    </div>
    </div>
   
</div>



</section>


{% endblock %}

Mobike/administracion/templates/administracion/sesion2.html
{% extends "administracion/base.html" %}

{%block head%}
ACCESO A USUARIOS
{%endblock%}
{%block script %}
<script>
  
$(function() {
    $("#formulario_usuarios").validate({
                  rules: { 
                          user: { required: true},
                          contrasenia: { required: true}
                          
                          },

                  messages : { 
                          user : { required: "Su usuario es requerido"},
                          contrasenia: { required: "Su contraseña es requerido"}
                            }
                          }
                          );

});
</script>

{% endblock %}
{% block nav %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark col-sm-6 col-md-6 col-lg-12">
    <a class="navbar-brand" href="/">MOBIKE</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
        <li class="nav-item active">
            <a class="nav-link" href="/">INICIO<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'administracion:registro' %}">REGISTRO</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'administracion:sesion' %}">ACCESO CORPORATIVO</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'administracion:sesion2' %}">ACCESO USUARIOS</a>
        </li>
        </ul>
    </div>
    </nav>
{%endblock%}

{% block content%}
<div class="container">
<h2>Acceso a Usuarios</h2>

<form method="POST" id="formulario_usuarios"class=" col-8">
    {% csrf_token %}
    <form>
  <div class="form-group">
    <label for="user">USUARIO</label>
    <input type="text" name="user" class="form-control" id="user" placeholder="Escriba aqui su usuario">
  </div>
  <div class="form-group">
    <label for="contrasenia">CONTRASEÑA</label>
    <input type="password" name="contrasenia"class="form-control" id="contrasenia" placeholder="Escriba aqui su contraseña">
  </div>
  <button type="submit" class="btn btn-primary">ACCEDER</button>

    <br>
  <br>
{% if m %}
  <div class="alert alert-danger" role="alert">
    {{m}}
</div>
{% endif %}

</form>
   


<hr />
<a href="{% url 'administracion:registro' %}">Si no tienes cuenta, Registrate</a>
</div>






{% endblock %}